num = int(10)
print('tipo int')
print(num)
num = float(10.80)
print('tipo   float')
print(num)
num = str(10)
print('tipo   dtring')
print(num)
num = str(10)
print('tipo string')
print(num)
num = bin(10)
print('tipo BInario')
print(num)
num = hex(10)
print('tipo Exadecimal')
print(num)
print('*****************************')
print('*****************************')
print('*****************************')
print('*****************************')
num = int('0b1010',2)
print('tipo reinvierte el binario')
print(num)
num = int('0xa',16)
print('tipo reinvierte el hexadecimal')
print(num)

num = abs(-7)
print('lo hace positivo')
print(num)

num = round(6.8)
print('refondea')
print(num)

num = len('fabian')
print('cuenta')
print(num)